name: Integration pipeline

on:
    push:
        branches:
            - master
        
jobs:
    frontend:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Install dependencies
              run: |
                cd frontend
                npm install

            - name: Check style
              run: |
                cd frontend
                npm run lint

            - name: Run tests
              run: |
                cd frontend
                npm test

            - name: Build frontend
              run: |
                cd frontend
                npm run build
              
    backend:
        runs-on: ubuntu-20.04
        env:   
            CYPRESS_PORT: ${{ secrets.PORT }}
            CYPRESS_MONGODB_URI: ${{ secrets.MONGODB_URI }}
            CYPRESS_TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
            CYPRESS_SECRET: ${{ secrets.SECRET }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Install dependencies (backend)
              run: |
                cd backend
                npm install

            - name: Install dependencies (frontend)
              run: |
                cd frontend
                npm install

            - name: Run tests
              run: |
                cd backend
                npm test

            - name: Start backend testing server
              run: |
                cd backend
                npm run start:test & #Start the backend server in the background

            - name: e2e tests
              uses: cypress-io/github-action@v6
              with:
                working-directory: frontend
                command: npm run test:e2e
                wait-on: http://localhost:3003

